#Button pinout:
"CAMERA_BUTTON_PIN" : 16 # GPIO pin that is connected to 'take photo' button
"EXIT_BUTTON_PIN"   : 26 # GPIO pin that is connected to 'exit' button (optional)

#light relay gpio pin
"LIGHT_RELAY" : 13

#GPIO Debounce Duration
# (This may help avoid "phantom presses" caused by electronic interference)
"DEBOUNCE_TIME"     : 0.05 # Min duration (seconds) button is required to be "pressed in" for.

# Take photos at this resolution:
"PHOTO_W"           : 800 #1920
"PHOTO_H"           : 800 #1152
#Note:
# - The max resolution for PiCamera v2, is: 3280x2464 , assuming you are running the latest firmware.
# - To upgrade your firmware, please run:
#   sudo apt-get dist-upgrade

# Resolution of the photo booth display:
"SCREEN_W"          : 800
"SCREEN_H"          : 480

# Camera setup
"CAMERA_ROTATION"   : 180 # Rotation of the camera
"CAMERA_HFLIP"      : True # When preparing for photos, the preview will be flipped horizontally.

# Primary folder to save images to (required):
"SAVE_RAW_IMAGES_FOLDER" : "photos"

# Additional locations where images will be saved to (optional):
"COPY_IMAGES_TO" : ["/media/pi/E86C-058F/"]

# Test purposes only:
"TESTMODE_AUTOPRESS_BUTTON" : False # Should the button be automatically pressed? (only used for testing)
